Seven-Mobile-Apps-In-Seven-Weeks/API/config/routes.rb
#---
# Excerpted from "Seven Mobile Apps in Seven Weeks",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit http://www.pragmaticprogrammer.com/titles/7apps for more book information.
#---
Rails.application.routes.draw do

  # Notes App -- ReactNative
  resources :notes
  get 'reverse_geocode/', to: 'reverse_geocode#reverse_geocode'

  # Todos App -- RubyMotion
  resources :todos

  # World Clock App -- Web
  get 'clock/time_zones'

  # Weather Forecast App -- iOS
  match 'weather/', to: 'weather#index', as: :weather, via: [:get, :post]
  get 'weather/location'
  get 'weather/:zip', to: 'weather#zip', as: :weather_for_zip

  # Currency Conversion App -- Android/Xamarin
  match 'convert/', to: 'convert#index', as: :convert, via: [:get, :post]
  get 'convert/:from_currency/:to_currency', to: 'convert#convert', as: :convert_result, from_currency: /[A-Za-z]{3}/, to_currency: /[A-Za-z]{3}/

  # Stock Quotes App -- Windows
  match 'stock_quotes/:symbols', to: 'stock_quotes#index', as: :stock_quotes, via: [:get]

end

Seven-Mobile-Apps-In-Seven-Weeks/API/app/controllers/weather_controller.rb
#---
# Excerpted from "Seven Mobile Apps in Seven Weeks",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit http://www.pragmaticprogrammer.com/titles/7apps for more book information.
#---
class WeatherController < ActionController::Base

  def index
    if request.post? and params[:zip]
      redirect_to weather_for_zip_url zip: params[:zip]
    else
      render "weather/index"
    end
  end

  def location
    # uncomment this to simulate slower responses
    # sleep 5.seconds
    @report = WeatherReport.for_location(params["name"])
    render "weather/zip"
  end

  def zip
    @report = WeatherReport.for_zip(params[:zip])
    render "weather/zip"
  end

end

Seven-Mobile-Apps-In-Seven-Weeks/API/app/views/weather/_forecast.html.erb
<li><strong><%= forecast.day %></strong> (<%= forecast.date %>) <%= forecast.text %> - High: <%= forecast.high %> Low: <%= forecast.low %></li>

Seven-Mobile-Apps-In-Seven-Weeks/API/app/views/weather/index.html.erb
<h1>Get The Weather</h1>

<%= form_tag(weather_url) do %>
  <div class="actions">
    <%= label_tag(:zip, "Enter Zip Code:") %>
    <%= text_field_tag(:zip) %>
    <%= submit_tag("Get Forecast") %>
  </div>
<% end %>

Seven-Mobile-Apps-In-Seven-Weeks/API/app/views/weather/zip.html.erb
<p>
<strong><%= @report.title %></strong>, temp: <%= @report.temp %>, conditions: <%= @report.current_conditions %>
</p>
<p>Forecast:</p>
<ul>
  <%= render partial: "forecast", collection: @report.forecasts %>
</ul>